# Generated by Django 5.2 on 2025-04-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('study_date', models.CharField(blank=True, max_length=20, null=True)),
                ('modality', models.CharField(blank=True, max_length=50, null=True)),
                ('study_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DicomImage',
        ),
    ]
